skip_branch_with_pr: true
version: '{build}-{branch}'
image: Visual Studio 2017
clone_script:
  - cmd: >-
      git clone --recursive -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER% 
install:
  - nuget restore
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
configuration: Debug
before_build:
  - git config --global user.email johndoe@example.com
  - git submodule update --init --recursive
build:
  verbosity: normal
after_build:
  - mkdir dotnet
  - copy Cement.Net\bin\Debug\cm.exe dotnet\cm.exe
  - copy Cement.Net\bin\Debug\cm.exe.config dotnet\cm.exe.config
  - xcopy files-common dotnet /s /i /Y
  - 7z a %APPVEYOR_REPO_COMMIT%.zip dotnet
artifacts:
  - path: $(appveyor_repo_commit).zip
deploy:
  provider: GitHub
  description: automatic release
  artifact: $(appveyor_repo_commit).zip
  auth_token:
    secure: 4ZYJdojxUj1R94fuci26zjd+Rs1Hmy5lPmPKi+/FWMwSJFTccFzgpsm3uHP/y4i8
  on:
    appveyor_repo_tag: true